apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube-clone-app
  template:
    metadata:
      labels:
        app: youtube-clone-app
    spec:
      containers:
        - name: youtube-clone-app
          image: kritika1012/youtube-clone-app:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred # Reference to the secret containing Docker registry credentials

