apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-app-service
spec:
  selector:
    app: youtube-clone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000 # Optional: Specify the NodePort you want to use
  type: NodePort
