apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-app-service
spec:
  selector:
    app: youtube-clone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000 # Specify the nodePort value you want to use (in the range 30000-32767)
  type: NodePort
